services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_web
    container_name: django_web
    command: sh /start.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.env.local
    depends_on:
      - redis
      - db
  db:
    image: postgres:15
    container_name: django_web_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env/.env.local
  redis:
    image: redis:7-alpine
    container_name: django_web_redis
  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_worker
    container_name: django_web_celery_worker
    command: sh /start-celeryworker.sh
    volumes:
      - .:/app
    env_file:
      - ./.env/.env.local
    depends_on:
      - redis
      - db
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_beat
    container_name: django_web_celery_beat
    command: sh /start-celerybeat.sh
    volumes:
      - .:/app
    env_file:
      - ./.env/.env.local
    depends_on:
      - redis
      - db
  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_flower
    command: sh /start-flower.sh
    container_name: django_web_celery_flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.env.local
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data: